services:
  stats-server:
    build:
      context: ./statistic/stats-service/
      dockerfile: ./Dockerfile
    image: stats-service:0.1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret_password
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    image: postgres:16.1
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ewm-service:
    build:
      context: ./main-service/
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret_password
    image: main-service:0.1
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password

volumes:
  pg_data: